rvm: 2.1

sudo: required

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

install:
  - bundle install --deployment --with integration

services: docker

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/bin/rubocop -v
  - /opt/chefdk/bin/foodcritic -V
  - /opt/chefdk/embedded/bin/rspec -v
  - /opt/chefdk/bin/kitchen -v
  - bundle exec kitchen create all

script:
  - /opt/chefdk/bin/rubocop
  - /opt/chefdk/bin/foodcritic . --exclude spec
  - /opt/chefdk/embedded/bin/rspec -r spec_helper.rb
  - bundle exec kitchen converge all
  - bundle exec kitchen verify all
