name              'mw_server_base'
maintainer        'Leandro Di Tommaso'
maintainer_email  'leandro.ditommaso@mikroways.net'
license           'Apache 2.0'
description       'Cookbook to apply the minimal configuration we want to have on every server.'
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           '0.1.0'

supports          'centos'
supports          'debian'
supports          'ubuntu'

depends           'apt',           '~> 2.9.2'
depends           'chef-vault',    '~> 1.3.2'
depends           'locale',        '~> 1.0.3'
depends           'ntp',           '~> 1.9.1'
depends           'postfix',       '~> 3.7.0'
depends           'rsyslog',       '~> 4.0.0'
depends           'sudo',          '~> 2.7.1'
depends           'timezone_lwrp', '~> 0.1.7'
depends           'ubuntu',        '~> 1.2.0'
depends           'users',         '~> 2.0.2'
